version: "3.8"
services:
  server:
    build: ./server
    command: npm run dev
    volumes:
      - ./server:/usr/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
